### ISSUE TITLE
Use flatten of elements to paths to reduce file size?

### ISSUE THREAD

**Issue by petulla** [bradoyler/d3-node#6]
https://gitlab.com/Rich-Harris/pathologist

Rich Harris just released this interesting repo. Integration might reduce the SVG size on the client. Might be worth experimenting.

**Comment by petulla** [comment]
This is also an interesting option for passing svgs through streams -> https://gitlab.com/Rich-Harris/svg-parser

**Comment by bradoyler** [comment]
This is something that could easily be used with the output of this module (much like svg2png), but don't see a need to add this into this module.
