### ISSUE TITLE
bug: path.merge is not a function

### ISSUE THREAD

**Issue by mbsimonovic** [bradoyler/d3-node#7]
tried to run [bl.ocks.org histogram example](https://bl.ocks.org/mbostock/3048450), with d3-v4, but it fails on ```svg.call(d3.axisBottom(x));``` with path.merge is not a function. Use the attachment to reproduce the issue. 
[d3-node-bug.zip](https://github.com/bradoyler/d3-node/files/437239/d3-node-bug.zip)

**Comment by bradoyler** [comment]
so, at first glance, ur options should include the instance of d3, like so:
```
var options = { 
  svgStyles: styles, 
  d3Module: d3 
};
```

Probably not as elegant as it could be. but it is needed to override the default version of d3 (v3.15.x)

**Comment by bradoyler** [comment]
Here's my rendered output:
![screen shot 2016-08-25 at 11 17 54 am](https://cloud.githubusercontent.com/assets/425966/17974827/9b287e2e-6ab5-11e6-9d89-1b6fb1d6515f.png)

using this gist: https://gist.github.com/bradoyler/85911182ee1698385e0f20087a62833b

**Comment by mbsimonovic** [comment]
yeah, that's better, at least some output, but not the same as pure d3 (attached index.html) 
![screen shot 2016-08-25 at 17 30 43](https://cloud.githubusercontent.com/assets/888008/17975361/adf329f8-6ae9-11e6-99d2-ce0e6957494a.png)

**Comment by bradoyler** [comment]
because u modified the script. See updated gist.

**Comment by mbsimonovic** [comment]
ah, my bad. all good now, so it's just passing d3 module as an option. feel free to close the issue

**Comment by bradoyler** [comment]
@mbsimonovic np, I think I may add this as an example unless you'd like to add it via pull request.
