### ISSUE TITLE
no layout

### ISSUE THREAD

**Issue by chovy** [bradoyler/d3-node#9]
```
    var pie=d3.layout.pie()
      .value(function(d){return d.percent})
      .sort(null);
```

this fails. d3.layout is undefined.

edit: nevermind. I found the issue:

```
    var D3Node = require('d3-node');
    var d3n = new D3Node();    // create instance
    var d3 = d3n.d3;
```

This solves my problem.

I see `d3-node` requires v3 of d3. Any plans to support v4?

**Comment by bradoyler** [comment]
already support v4, like so: 
https://github.com/bradoyler/d3-node/blob/master/examples/v4.line-chart.js
